# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DealifyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!
   pod 'MapboxMaps', '~> 10.0'
  # Pods for DealifyApp

  target 'DealifyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DealifyAppUITests' do
    # Pods for testing
  end

end
